Document: libhermit
Title: Debian libhermit Manual
Author: <insert document author here>
Abstract: This manual describes what libhermit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libhermit/libhermit.sgml.gz

Format: postscript
Files: /usr/share/doc/libhermit/libhermit.ps.gz

Format: text
Files: /usr/share/doc/libhermit/libhermit.text.gz

Format: HTML
Index: /usr/share/doc/libhermit/html/index.html
Files: /usr/share/doc/libhermit/html/*.html
