name: Format check

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

jobs:
  check:
    name: Format check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]
        include:
          - os: ubuntu-latest
            rust: 'nightly'
            components: 'rustfmt'
            targets: 'x86_64-unknown-linux-gnu'


    steps:
      - uses: hecrj/setup-rust-action@v1.3.1
        with:
          rust-version: ${{ matrix.rust }}
          components: ${{ matrix.components || '' }}
          targets: ${{ matrix.targets || '' }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check Formatting
        run: cargo fmt -- --check
