name: Tests without SMP support (nightly)

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

jobs:
  build:
    name: Tests without SMP support
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]
        include:
          - os: macOS-latest
            rust: 'nightly'
            components: 'rust-src, llvm-tools-preview'
            targets: 'x86_64-apple-darwin'
          - os: windows-latest
            rust: 'nightly'
            components: 'rust-src, llvm-tools-preview'
            targets: 'x86_64-pc-windows-msvc'
          - os: ubuntu-latest
            rust: 'nightly'
            components: 'rust-src, llvm-tools-preview'
            targets: 'x86_64-unknown-linux-gnu'


    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: ${{ matrix.components || '' }}
          targets: ${{ matrix.targets || '' }}
      - name: Checkout rusty-hermit
        uses: actions/checkout@v2
        with:
          repository: 'hermitcore/rusty-hermit'
          ref: 'master'
          submodules: 'true'
      - name: Remove submodule libhermit-rs
        run: rm -r libhermit-rs
        if: ${{ ( matrix.os == 'macOS-latest' ) || ( matrix.os == 'ubuntu-latest' ) }}
      - name: Remove submodule libhermit-rs (windows)
        run: git rm -r libhermit-rs
        if: ${{ matrix.os == 'windows-latest' }}
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          path: 'libhermit-rs'
      - name: Check Cargo availability
        run: cargo --version
      - name: Cargo Test libhermit-rs (Unittests on Host)
        run: cargo test --lib --target x86_64-unknown-linux-gnu
        working-directory: libhermit-rs
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Install qemu/nasm (apt)
        run: sudo apt-get update --fix-missing && sudo apt-get install qemu-system-x86 nasm
        if: ${{ matrix.os == 'ubuntu-latest' }}
      # Note: The add-path must be kept in sync with the version of binutils installed by homebrew
      - name: Install qemu/nasm (macos)
        run: |
          brew install qemu nasm
        if: ${{ matrix.os == 'macOS-latest' }}
      - name: Install nasm (windows)
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install nasm 
        if: ${{ matrix.os == 'windows-latest' }}
      # Note: force version to 2020.08.14, as the november version seems to be broken.
      - name: Install qemu (windows)
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install qemu --version=2020.08.14
        if: ${{ matrix.os == 'windows-latest' }}
        # Note: The november release of qemu installs into 'C:\Program Files (x86)' by default, so keep that in mind when updating qemu
      - name: Set path to qemu/nasm (Windows)
        run: |
          echo "C:\Program Files\qemu" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\nasm" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        if: ${{ matrix.os == 'windows-latest' }}
      - name: Building dev version
        run:
          cargo build --manifest-path examples/demo/Cargo.toml --no-default-features --target x86_64-unknown-hermit
      - name: Building release version
        run:
          cargo build --manifest-path examples/demo/Cargo.toml --no-default-features --target x86_64-unknown-hermit --release
        env:
          RUSTFLAGS: -Clinker-plugin-lto
      - name: Build loader (unix)
        working-directory: loader
        run: make
        if: ${{ ( matrix.os == 'macOS-latest' ) || ( matrix.os == 'ubuntu-latest' ) }}
      # Workaround since makefile doesn't work when using powershell
      - name: Build loader (windows)
        working-directory: loader
        run: |
          cargo build -Z build-std=core,alloc --target x86_64-unknown-hermit-loader.json
          $VAR_RUSTC_SYSROOT = (rustc --print sysroot)
          echo "Sysroot - $VAR_RUSTC_SYSROOT"
          $LLVM_OBJCOPY = ((Get-ChildItem -Path $VAR_RUSTC_SYSROOT -Include llvm-objcopy.exe -File -Recurse -ErrorAction SilentlyContinue)).Fullname
          echo "LLVM Objcopy - $LLVM_OBJCOPY"
          Invoke-Expression "$LLVM_OBJCOPY --strip-debug -O elf32-i386 target/x86_64-unknown-hermit-loader/debug/rusty-loader"
        if: ${{ matrix.os == 'windows-latest' }}
      - name: Test dev version
        run:
          qemu-system-x86_64 -display none -smp 1 -m 128M -serial stdio -kernel loader/target/x86_64-unknown-hermit-loader/debug/rusty-loader -initrd target/x86_64-unknown-hermit/debug/rusty_demo -cpu qemu64,apic,fsgsbase,rdtscp,xsave,fxsr
      - name: Test release version
        run:
          qemu-system-x86_64 -display none -smp 1 -m 128M -serial stdio -kernel loader/target/x86_64-unknown-hermit-loader/debug/rusty-loader -initrd target/x86_64-unknown-hermit/release/rusty_demo -cpu qemu64,apic,fsgsbase,rdtscp,xsave,fxsr
